services:
  debonk-db:
    image: postgres:15
    restart: always
    container_name: debonk-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: pposttgresxdb
      POSTGRES_PASSWORD: 3353
      POSTGRES_DB: nest
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=goodadmin@pouchpay.xyz
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4forpouch
    ports:
      - "5050:80"
    depends_on:
      - debonk-db
#     networks:
#       - sun_network
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: sun-snipe-tg-bot
#     restart: always
#     environment:
#       - PORT=3009
#     ports:
#       - "3009:3009"
#     depends_on:
#       - sun-snipe-bot-db
#     volumes:
#       - ./src:/app/src
#     networks:
#       - sun_network
# networks:
#   sun_network:
